### ISSUE TITLE
can't start with minus when precision = 0

### ISSUE THREAD

**Issue by Ahmed-Alsalim** [coders-tm/vue-number-format#63]
very similar behavior to #28. if precision is set to 0 it doesn't accept typing minus "-" if input field is empty. can still hit minus after typing the number or paste negative number. I'm using vue 2 but I think it happens in vue 3 as well as it can be replicated in playground by simply changing precision to 0.

**Comment by dipaksarkar** [comment]
Use latest version, I have fix the issue.

**Comment by Niccober** [comment]
@dipaksarkar In the playground, this exact problem is still an issue. Is the playground using the latest version?

Precision 2 works:
![Image](https://github.com/user-attachments/assets/59a2043d-ba2b-44d8-a1e9-aee16b9f2f83)

Precision 0 does not work (completely removing the precision value yields the same result):
![Image](https://github.com/user-attachments/assets/b4891783-0cc6-4980-ac13-763d571a691e)

In the latter case entering a `-` into the field is not possible.

Can you please also update the [q-number Quasar App Extension](https://github.com/coders-tm/quasar-app-extension-qnumber) with the latest version of the core package so the fix is available there as well? Would be highly appreciated!

**Comment by Niccober** [comment]
@dipaksarkar Any update on this?
