### ISSUE TITLE
Error whit Vu3 (vite) and library

### ISSUE THREAD

**Issue by macJames976** [coders-tm/vue-number-format#9]
I have same code:

`import { Number } from "@coders-tm/vue-number-format";`

but i have this error from IDE:

```
Could not find a declaration file for module '@coders-tm/vue-number-format'. 'C:/Users/username/folder1/projectfolder/node_modules/@coders-tm/vue-number-format/dist/index.cjs.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/coders-tm__vue-number-format` if it exists or add a new declaration (.d.ts) file containing `declare module '@coders-tm/vue-number-format';`ts(7016)
```

**Comment by dipaksarkar** [comment]
@macJames976 It doesn't support typescript. :(

**Comment by macJames976** [comment]
I don’t use typescript…

**Comment by dipaksarkar** [comment]
@macJames976 It's seams that you have import `Number` which is not exported. Only you can import followings: 

1.  number,
2. vNumber,
3. options,
4. NumberFormat

And the issue you are getting because you selected `vue-ts` when created a vite project. You have to select `vue` to use this plugin to vite project.
